# this is comment - this is my first workflow
name: workflow1
on:
  workflow_dispatch:
  push:
env:
  greetings: Hi There
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      last_name: kawamoto
      greetings: GoodDay
    steps:
      - name: this is step1
        run: |
          echo $greetings! $name $last_name is the owner of $GITHUB_REPOSITORY for application ${{ vars.APP_NAME }} .
          echo Reachout to $name for any updates. Thank you.
          echo This step is running on $RUNNER_OS on instance $RUNNER_NAME
          sleep 5
        env:
          name: malie
          greetings: Aloha
      - name: second step
        run: |
          uname -a
          echo "hello from step2-job1"
          echo $greetings! $name $last_name can be contacted if this is not job1.
          cat /etc/os-release
          sleep 5
      - run: echo "step3" 
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: this is step1
        run: |
          echo $HOSTNAME
          echo $greetings! $name $last_name is the owner of this repo. 
                    echo This step is running on $RUNNER_OS on instance $RUNNER_NAME
          sleep 5
      - name: second step
        run: |
          echo "hello from step2-job2"
          cat /etc/os-release
          sleep 5
      - run: echo "step3" 
