# this is comment - this is my first workflow
name: workflow1
on:
  workflow_dispatch:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: this is step1
        run: |
          echo $HOSTNAME
          sleep 20
      - name: second step
        run: |
          echo "hello from step2-job1"
          cat /etc/os-release
          sleep 20
      - run: echo "step3" 
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: this is step1
        run: |
          echo $HOSTNAME
          sleep 20
      - name: second step
        run: |
          echo "hello from step2-job2"
          cat /etc/os-release
          sleep 20
      - run: echo "step3" 
