# this is comment - this is my first workflow
name: pipeline
on:
  workflow_dispatch:
  push:
  #pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    #needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: this is step1 of build
        run: |
          echo "step1"
          ls -al
      - name: second step
        if: runner.os == 'Linux' 
        run: |
          echo "step2" 
          echo The oper system is $RUNNER_OS. 
          sleep 5
        #if: github.event_name == 'push'
      - name: third step
        if: runner.os == 'Windows'
        run: echo "step3" 
  test:
      runs-on: ubuntu-latest
      #continue-on-error: true
      needs: build
      steps:
      - name: this is step1 of test
        run: echo "step1" 
        #continue-on-error: true
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
  stage:
      runs-on: ubuntu-latest
      needs: test
      if: ${{ always() }}
      steps:
      - name: this is step1 stage
        run: echo "step1" 
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
  deploy:
      runs-on: ubuntu-latest
      needs: [ stage,test ]
      steps:
      - name: this is step1 deploy
        run: echo "step1" 
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
