# this is comment - this is my first workflow
name: pipeline
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: this is step1
        run: ech "step1" 
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
  test:
      runs-on: ubuntu-latest
      steps:
      - name: this is step1
        run: echo "step1" 
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
