# this is comment - this is my first workflow
name: pipeline
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    #needs: deploy
    steps:
      - name: this is step1 of build
        run: echo "step1" 
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
  test:
      runs-on: ubuntu-latest
      continue-on-error: true
      needs: build
      steps:
      - name: this is step1 of test
        run: ech "step1" 
        continue-on-error: true
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
  stage:
      runs-on: ubuntu-latest
      #needs: test
      steps:
      - name: this is step1 stage
        run: echo "step1" 
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
  deploy:
      runs-on: ubuntu-latest
      needs: [ stage,test ]
      steps:
      - name: this is step1 deploy
        run: echo "step1" 
      - name: second step
        run: |
          echo "step2" 
          sleep 10
      - run: echo "step3" 
