# this is comment - this is my workflow for windows
name: workflow3win
on:
  workflow_dispatch:
  push:
jobs:
  job1:
    runs-on: windows-2019
    steps:
      - name: this is step1
        run: |
          echo "hello from step1"
          sleep 10
      - name: second step
        run: |
          echo "hello from step2"
          echo %variable%
          sleep 10
      - run: echo "step3" 
